### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by mk4y** [marcelveldt/plugin.audio.spotify#10]
![2016-09-19-191615_1336x353_scrot](https://cloud.githubusercontent.com/assets/8222191/18641697/0b8b267a-7e9e-11e6-8f87-171d24a0dbcf.png)

Lately I'm getting that error on multiple machines running version 1.0.22 of your addon. Authorization works perfectly fine but it then fails to list the directories. Tried it on x86 and armv7 both running arch linux as well as kodi-jarvis and -krypton (fresh install).

Nevertheless it was the best spotify addon I've used so far and I'd like to thank you for your hard work!

**Comment by en00x** [comment]
I get the same exception on my RPi running Kodi 16.
[KodiLog.txt](https://github.com/marcelveldt/plugin.audio.spotify/files/486315/KodiLog.txt)

**Comment by marcelveldt** [comment]
hmm strange... looks like the spotify sdk failed to load. I can't reproduce the issue on my libreelec x86 machine but I'll give it a test on my pi tomorrow

**Comment by en00x** [comment]
Yes really strange. I tried it with with Version 0.19 - 0.22 and Python 2.7.9 and 2.7.12, but always the same error. Then i tried it with a fresh install of rapsbian and it works now, but i have no clue what it was in the end

**Comment by piater** [comment]
I got the same error. In my case, the problem was a name clash: playbackservice.py tries to import MainLoop from the spotify module, but instead of ./libs/spotify it found the spotify module from pyspotify (from the mopidy project), which I had independently installed system-wide.

I got it to work by changing "sys.path.append(full_path)" to "sys.path.insert(0, full_path)" in resources/utils.py.

However, I think a better solution would be to refrain from stashing python modules away in (non-module) subdirectories and avoid messing with sys.path, and instead organizing all code into a module hierarchy and using explicit relative imports to avoid name clashes.

For explicit relative imports see https://docs.python.org/2.5/whatsnew/pep-328.html; note that imports are **not** absolute by default in Python 2.7 (but they are in Python 3).

**Comment by 132Garfield** [comment]
After installing add-on adding Spotify Premium login credentials, I'm getting this error as well . Looking for a novice fix if possible. Kodi error log here... https://paste.ubuntu.com/23730575/
Says "plugin failed to load". I saw a mention of needing to exit Kodi and go into the web browser on the RasPi to somehow verify my Spotify Premium account. Any help much appreciated.

**Comment by flakey-bit** [comment]
I think my pull request https://github.com/marcelveldt/plugin.audio.spotify/pull/17 might fix this issue.
