### ISSUE TITLE
Include dynamic custom playlists from Spotify

### ISSUE THREAD

**Issue by sebastian-steinmann** [marcelveldt/plugin.audio.spotify#27]
Spotify has daily mix and things like "Your summer rewind". Any way to include them in the listing somehow?

**Comment by marcelveldt** [comment]
Yeah, I was looking for them in the web API but I couldn't find them there.
Maybe open up a feature request at the Spotify devs who create the web API ?

https://developer.spotify.com/web-api/endpoint-reference/

**Comment by sebastian-steinmann** [comment]
Seems this is already requested to no avail:
https://github.com/spotify/web-api/issues/324

**Comment by marcelveldt** [comment]
Hmm, too bad that Spotify is a bit ignoring the opensource community. I had to switch to the opensource librespot implementation for playback support because theý still lack a succeeder for libspotify which is EOL.

Maybe one day they'll add this in, if they do I'll be happy to make the change in the code.

**Comment by marcelveldt** [comment]
I'll close this one for now. Feel free ro reopen or recreate the request once this is available in the spotify api.
