### ISSUE TITLE
Doesn't seem to work well with Kodi profiles

### ISSUE THREAD

**Issue by Alphix** [marcelveldt/plugin.audio.spotify#31]
I have a Kodi installation with two profiles. The spotify plugin works after I've just started Kodi, but if I switch to the other profile and back again, there are leftover librespot zombie processes on the system and the spotify plugin is unable to play any tracks (the system log complains about a port being in use, so I'm guessing the zombie processes are hogging that port).

**Comment by marcelveldt** [comment]
Please test again with the latest release. This issue should be fixed.

**Comment by Alphix** [comment]
Nope, doesn't seem to be fixed. Now I get spotty zombie processes instead...

**Comment by marcelveldt** [comment]
OK, I'll take a look at it later this week. User switching is kind of a pain to implement.

**Comment by marcelveldt** [comment]
Would it be possible to provide me your kodi logfile after you did some user switching ?
btw, you can ignore the spotty processes, they will be cleaned up automatically

**Comment by Alphix** [comment]
Logfile attached....the only thing which looks suspicious is the "script didn't stop in 5 seconds - let's kill it" part...note that right now Kodi seems to crash on user switch with the spotify plugin enabled rather than spotify just not working anymore (that's why the log file is so short....kodi crashed).

[kodi.txt](https://github.com/marcelveldt/plugin.audio.spotify/files/1180728/kodi.txt)

**Comment by marcelveldt** [comment]
Like I said, user switching is very sensitive.

**Comment by marcelveldt** [comment]
Hmmm, your log is a bit confusing. It wants to shutdown right after it started. Did you switch the user right after starting up Kodi ?

Maybe you should wait a bit longer until you switch ?
Python scripts are executed in alphabetically order by Kodi. So at login/startup it will start each python service (including spotify). If you shutdown Kodi or switch a user it send a shutdown command to each python add-on but this is done again one-by-one and not all at once. So if add-on 1 is still processing something it blocks the shutdown for other addons too.

I made sure that the add-on responds very quickly when Kodi requests a shutdown (within 1 second all background processing is ended) but the startup takes a few seconds and that is blocking. 

So in theory if the add-on is in it's blocking, startup state and Kodi tries to send a shutdown it will not respond in time and Kodi kills the process and that's exactly what bring it into a useless state because the web proxy port is still hogged by the previous process.

Like I said I will look into it but this is a very sensitive process.

**Comment by Alphix** [comment]
Sorry for the long delay, this kind of fell off my radar.

Yes, in the log I provided I switch users almost immediately....but the results are exactly the same if I wait a minute and then perform the user switch (I can provide a separate log if necessary).

**Comment by marcelveldt** [comment]
new version will be available on the repo within a few minutes, can you give that a try ?
