### ISSUE TITLE
Spotify Free Account

### ISSUE THREAD

**Issue by fabianHAW** [marcelveldt/plugin.audio.spotify#41]
hey,

is there any way to use this add on with a free (non premium) spotify account? is it not possible, because spotify does not open the music streams for free accounts? or why do i need a premium account for this add on?

greetings :)
fabian

**Comment by marcelveldt** [comment]
As far as I'm aware using a free account will not work because of the simple fact that Spotify doesn't not open their API access for free accounts.
You can give it a try but I'm pretty sure it won't work at all.

It's the same as with every other implementation. For example as Sonos system will also not allow you to use a free account.

If you want to enjoy music, you'll have to pay a few bucks a month.
Believe me, it's worth it.

**Comment by fabianHAW** [comment]
ok, thanks for this advice :) i just thought about this circumstance, that they do not open the api..i tried it one time and used my credentials of my free account, but nothing happened.
