### ISSUE TITLE
Unable to find libspotify

### ISSUE THREAD

**Issue by lsouchet** [marcelveldt/plugin.audio.spotify#6]
Hello,
First, thanks for your work.

I installed your spotify addon 1.0.5 on my android TV 5.1 ARM running Kodi 15.2, but I encountered an issue.
I managed to connect to my spotify premium account through the web browser.
When I go back to Kodi and start the addon, it takes some time and then pops up a message telling me:
Login error: Platform not supported for playback, continuing without playback support.

I then can access my spotify library and all spotify playlists, but when I start a song, only 30 seconds are playing, and the next song starts.

By looking at the log files, it appears that the libspotify is not found.
However, by inspecting the installation folder, in /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.spotify/resources/dlls/android.arm, there are 3 files:
libspotify.so, libspotify.so.12, and libspotify.so.12.1.51

Here is my [log file](http://pastebin.com/wffEikvM), everythin happens around line 650.

Is it something you are aware of? 
Do you have any idea how to solve it?

Thanks for your help!

**Comment by marcelveldt** [comment]
I never had the chance to test it on newer Android hardware. The libspotify implementation is really old and deprecated but I have to use it untill they released the support for playback in the webapi.

There is a little something you might want to test:

Open the file resources\utils.py in notepad++ 
At line 103 is the definition for your platform: Android ARMv7

There are 3 paths specified there to look, please alter the line so that is only contains one path and test the different paths one by one.

So your first test should look like this:

(Platform.ANDROID, Architecture.ARMV7) : ["resources/dlls/android/arm"],

If it fails to work with all three paths we'll have to find somebody prepared to build the libspotify libraries for the newer android platforms.

**Comment by lsouchet** [comment]
Hello,
first thanks for your quick answer.
I have tried to use each lib path successfully, unfortunately it didn't solve my problem, and when looking at the kodi log file after each try, it seems it didn't manage to load the lib.
How the newer android hw configuration changes from the one you used to build android armv7 lib?

**Comment by marcelveldt** [comment]
In that case you're out of luck and it isn't going to work.
The libspotify is outdated and besides the native android library there is no alternative available.

I think/believe that the current version of the libspotify library for android is compiled for arm5/6 only.

**Comment by plao** [comment]
Hi Marcel...

many congrats for your GREAT sw!

Unfortunately I have the same issue reported by lsouchet :-(, the error message "Platform not supported for playback, continuing without playback support.", of course error code 999.

Sorry but I've not understand what kind of edit will be done on the cfg file "resources\utils.py", here is the content (the numbers are the rows #):

**103 (Platform.ANDROID, Architecture.ARMV6) : ["resources/dlls/android/arm"],
104 (Platform.ANDROID, Architecture.ARMV7) : ["resources/dlls/android/arm"],
105 (Platform.ANDROID, Architecture.X86) : ["resources/dlls/android/arm"],
106 (Platform.ANDROID, Architecture.X86_64) : ["resources/dlls/android/arm"],
107 (Platform.ANDROID, Architecture.AARCH64) : ["resources/dlls/android/arm"],**

Thanks in advance if you can help me, in the meantime I'll take a look in the posts on [(http://forum.kodi.tv/showthread.php?tid=265356)]...

Have a great day!

Best,
Giandomenico
