### ISSUE TITLE
Menu navigation exceedingly slow

### ISSUE THREAD

**Issue by loadncode** [marcelveldt/plugin.audio.spotify#74]
Hi, firstly I have only recently begun using this addon and it worked flawlessly for around 24 hours. However unfortunately I now have an issue where every request made via the addon's menu system takes an insanely long time to return. I'm certain this is nothing to do with my internet connection and I doubt it's even anything to do with Spotify's servers. For instance simply clicking on "Playback device" results in a perhaps 30s wait until the submenu appears. But once I do manage to plow through the submenus and get an album to play, then playback works fine and it continues onto the next song without delay.

I have a feeling that the issue begun when I upgraded the addon. I'm not certain of this but at one point I definitely did have zip files present in ~/.kodi/addons/packages for both 1.1.50 and (I think) 1.1.49. Unfortunately before I realised that this could have been the cause I got frustrated and deleted the whole of ~/.kodi! But also looking through the latest commit it looked like some of the changes made corresponded with some of the errors that were cropping up in the log file.

Anyway here is a debug log:  [kodi.log](https://github.com/marcelveldt/plugin.audio.spotify/files/1866094/kodi.log). By the way I have spotty / Spotify Connect disabled in the addon.

**Comment by fportegies** [comment]
Same here with very slow menu navigation, not able tot play anything. Liked the addon, now its useless.
Here is a log from Kodi on raspberry pi.
[kodi_log.txt](https://github.com/marcelveldt/plugin.audio.spotify/files/1866236/kodi_log.txt)

**Comment by gpchampion** [comment]
Im running this latest version 1.1.50 on OSMC, Libreelec, Android/Kodi and all are behaving in the same way. Very slow, taking 2 minutes to display next menu items. The playback is also slow after it assembles a playlist, and sometimes no sound until you skip to the next track. Something has gone very wrong as it seems its stuck in some loop and then times out. Old version was fine, except it continued to ask for credentials on OSMC across system restarts. Noticed logs keep logging me back into spotify all the time. Android behaves in the same way except it shows a browser window for auth all the time, which I think was due to the OS architecture. Marcel knows what he is doing as I've followed this for ages, so Im sure he'll repair it with logs etc in due course. I'll post logs up at some point.

**Comment by marcelveldt** [comment]
Already looking at it, to be continued today

**Comment by gpchampion** [comment]
Thanks Marcel. Hope its an obvious issue and doesnt take you too long! Cheers!

**Comment by gpchampion** [comment]
If you need it testing on OSMC S905x/LibreElec 8.2 S905x/Android S905x/ all using Kodi 17.6 shout!

**Comment by marcelveldt** [comment]
new version 1.1.52 will be on the repo within 10 minutes, that should fix all issues

**Comment by loadncode** [comment]
Thanks very much Marcel, yes all has been working fine for me since updating to 1.1.52 and restarting Kodi.

**Comment by gpchampion** [comment]
tested on OSMC S905x ok, although a few tracks played with no sound. Skipped forwards to next track and back again, I was able to play them. Strange! Restarted OSMC and will try again Monday on other S905x and S912 if I can. Thanks for making it work again Marcel.

**Comment by gpchampion** [comment]
Ok, so random playlists from Spotify on OSMC using 1.1.52 result in silent tracks at random. If you skip back to the start or onto the next track, then it plays ok. It seems random as far as I can make out. This wasn't happening before I don't believe?
